version: "3.4"

services:
  backend-old:
    image: heartbeat_backend:latest
    container_name: backend-old
    ports:
      - 3001:3001
    restart: always
    networks:
      - default
  frontend-old:
    image: heartbeat_frontend:latest
    container_name: frontend-old
    ports:
      - 4325:80
    depends_on:
      - backend-old
    restart: always
    networks:
      - default
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    driver: bridge

