env:
  JAVA_VERSION: "17"
  GRADLE_VERSION: "7.2"
  CODACY_PROJECT_TOKEN: "rewrewrewrewrewrewrew"

steps:
  - label: ":lock: Security Check"
    command: >
      docker run --rm -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest  git file:///pwd --since-commit HEAD  --fail

  - label: ":rocket: Backend Check"
    command: ./infra/buildkite/app-check && echo 'Backend Check complete'
    artifact_paths: "project/build/libs/*.jar"
    plugins:
      - docker-compose#v3.5.0:
          run: gradle
          config: .buildkite/docker-compose.yml
