env:
  RETENTION_DAYS: "10"

steps:
  - label: ":lock: Check security"
    command: ./.buildkite/ops/check security

  - label: ":rocket: Check backend"
    command: ./.buildkite/ops/check backend

  - label: ":mag: Check frontend license"
    commands: ./.buildkite/ops/check frontend-license

  - label: ":mag: Check backend license"
    commands: ./.buildkite/ops/check backend-license
    plugins:
      - artifacts#v1.9.0:
          upload:
            - "backend/build/reports/dependency-license/**/*"
          name: "backend-license-report"
          expire_in: "${RETENTION_DAYS} days"

  - wait
  - label: ":rocket: Deploy infra"
    if:  build.branch == "main" && build.message =~ /\[infra\]/
    env:
      AWSHost: "$AWS_HOST"
      AWSAccountId: "$AWS_ACCOUNT_ID"
      AWSRegion: "$AWS_REGION"
    command: ./.buildkite/ops/deploy infra

  - wait
  - label: ":rocket: Build backend"
    branches: main
    command: ./.buildkite/ops/build backend

  - wait
  - label: ":rocket: Build stub"
    key: "Build stub"
    branches: main
    command: ./.buildkite/ops/build stub

  - label: ":rocket: Deploy stub"
    branches: main
    depends_on: "Build stub"
    command: ./.buildkite/ops/deploy stub

  - wait
  - label: ":rocket: Deploy prod"
    command: ./.buildkite/ops/deploy prod

