steps:
  - label: ":lock: Security Check"
    command: >
      docker run --rm -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest  git file:///pwd --since-commit HEAD  --fail

  - label: ":rocket: Backend Check"
    command: ./infra/buildkite/app-check && echo 'Backend Check complete'
