env:
    JAVA_VERSION: "19"
    GRADLE_VERSION: "7.2"

steps:
  - label: ":lock: Security Check"
    command: >
      docker run --rm -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest  git file:///pwd --since-commit HEAD  --fail
  
  - label: ":rocket: Backend Check"
    command: |
      cd /app/backend
      ./gradlew clean check
      ./gradlew clean build
      export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}
      bash <(curl -Ls https://coverage.codacy.com/get.sh)
    workdir: /app/backend

