env:
  RETENTION_DAYS: "10"
steps:
  - label: ":lock: Security Check"
    command: ./.buildkite/app-check security

  - label: ":rocket: Backend Check"
    command: ./.buildkite/app-check backend

  - label: ":mag: Frontend License Check"
    commands: ./.buildkite/app-check frontendLicenseCheck

  - label: ":mag: Backend License Check"
    commands: ./.buildkite/app-check backendLicenseCheck
    plugins:
      - artifacts#v1.9.0:
          upload:
            - "backend/build/reports/dependency-license/**/*"
          name: "backend-license-report"
          expire_in: "${RETENTION_DAYS} days"

  - label: ":computer: Frontend Check"
    command: ./.buildkite/app-check frontend

  - label: ":computer: License compliance check"
    commands:
      - cd frontend
      - npm install
      - npm run license-compliance
