env:
    JAVA_VERSION: "19"
    GRADLE_VERSION: "7.2"

steps:
  - label: ":lock: Security Check"
    command: >
      docker run --rm -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest  git file:///pwd --since-commit HEAD  --fail
  
  - label: ":rocket: Backend Check"
    command: >
      docker run
      --rm
      -v $(pwd)/backend:/app
      gradle:jdk${{ JAVA_VERSION }}
      ./gradlew clean check build
  # - label: ":chart_with_upwards_trend: Upload Test Report to Codacy"
  #   command: >
  #     bash <(curl -Ls https://coverage.codacy.com/get.sh)
  #   plugins:
  #     - "codacy#v2.0.0":
  #         coverage_report_path: "backend/build/reports/jacoco/test/jacocoTestReport.xml"

